### ISSUE TITLE
¿Cómo se ejecuta el LSP para otros editores?

### ISSUE THREAD

**Issue by tralph3** [uqbar-project/wollok-lsp-ide#163]
Quisiera saber si hay algún ejecutable que me permita correr el servidor por separado de VSCode para uso en otros editores.

Compilé el proyecto con node, y probé ejecutar el archivo `server.js` con la flag `--stdin`. Eso parece funcionar, pero cuando intento usarlo con mi cliente de LSP (eglot) tira el siguiente error y falla instantáneamente:

```
[stderr]  /home/tralph3/Downloads/extension/server/out/server.js:27
[stderr]  config.forEach(config => environmentProvider.inferTypes = config.typeSystem.enabled);
[stderr]                                                                   ^
[stderr]  
[stderr]  TypeError: Cannot read properties of null (reading 'typeSystem')
[stderr]      at /home/tralph3/Downloads/extension/server/out/server.js:27:66
[stderr]      at Object.next (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Observable.js:54:25)
[stderr]      at ConsumerObserver.next (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
[stderr]      at Subscriber._next (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26)
[stderr]      at Subscriber.next (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
[stderr]      at /home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34
[stderr]      at Object.errorContext (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
[stderr]      at Subject.next (/home/tralph3/Downloads/extension/server/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24)
[stderr]      at /home/tralph3/Downloads/extension/server/out/server.js:100:16
[stderr]  
[stderr]  Node.js v21.7.1

----------b---y---e---b---y---e----------
[stderr]  
[stderr]  
[stderr]  nil
[stderr]  nil
[stderr]  Process EGLOT (tralph3/nil) stderr finished
```

Eglot también se queja de lo siguiente:

```
[eglot] Connected! Server `EGLOT (tralph3/nil)' now managing `nil' buffers in project `tralph3'.
[eglot] (warning) Server tried to register unsupported capability `workspace/didChangeConfiguration'
[eglot] (warning) Server tried to register unsupported capability `workspace/didChangeWorkspaceFolders'
[jsonrpc] Server exited with status 1
[eglot] (warning) Not auto-reconnecting, last one didn't last long.
```

El comando que estoy utilizando para ejecutar el server es `node /home/tralph3/Downloads/extension/server/out/server.js --stdio`. Está tirado en mi directorio de descargas porque estoy haciendo pruebas.

¿Estoy haciendo algo mal? Gracias.

**Comment by fdodino** [comment]
Hola @tralph3 ,
         lo que yo tomaría es el archivo [client](https://github.com/uqbar-project/wollok-lsp-ide/blob/master/client/src/extension.ts) de este proyecto para ver cómo invocar al server. El problema puntual acá es el server no tiene un archivo de configuración y se rompe.
Saluditos
Fer

**Comment by tralph3** [comment]
Hola, estuve leyendo el código y no llego a ver dónde se carga un archivo de configuración. Veo que detecta cambios en los archivos `.clientrc`. ¿Es eso? ¿Dónde espera encontrar el archivo?

Para ser claro, el LSP debería poder ejecutarse en una terminal independientemente del editor, y luego un cliente se conecta y comienza a comunicarse con él.

No he tenido problemas con otros LSP, y no estoy seguro si estoy haciendo algo mal, o si fue diseñado para uso exclusivo con VSCode.

**Comment by fdodino** [comment]
Hola, 
         el archivo `.clientrc` supongo que lo genera en base al `package.json`: [acá](https://github.com/uqbar-project/wollok-lsp-ide/blob/dfec6ed514756fc4899c7858eb3f71b1fb105c7e/package.json#L61) es donde hacemos una definición de los valores y eso se puede cambiar desde el VSC mediante `Ctrl` + `,` (Settings).

Yendo a tu pregunta puntual, 
- Wollok LSP IDE es una implementación donde tomamos [este proyecto de ejemplo](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) de VSC y lo fuimos avanzando en base al parser/interpreter que se armó en Wollok para typescript
- eso explica también por qué no nos encontramos con ese problema y por qué no necesitamos saber demasiado cómo ejecutarlo en forma independiente del cliente de VSC
- está exclusivamente pensado para VSC? No, pero nuestro objetivo está fuertemente orientado a que funcione bien para VSC. No tenemos un equipo grande de desarrolladores, somos básicamente 3 personas estables + colaboradores que nos ayudan tirando PRs, así que la etapa exploratoria de otros IDEs la dejamos para cuando podamos terminar de sumar las herramientas que queremos

**Comment by tralph3** [comment]
Perfecto, revisaré por mi cuenta entonces como hacerlo y si se necesita hacer alguna modificación al código hago una contribución. Saludos.

**Comment by tomi2108** [comment]
@tralph3 Llegaste a algún lado con esto? Yo estuve haciendo unas pruebas para implementar un plugin de NeoVim pero el LSP me responde `Error: Missing workspace folder!` cuando en la request de init estan las veo bien.

**Comment by tralph3** [comment]
Hice algunas pruebas. Parece que el server intenta registrar capacidades que el cliente no soporta. Conseguí establecer una conexión sin que se muera el server, pero no funciona, el cliente envía requests y el server no las responde.

El primer fallo que tiene es [acá](https://github.com/uqbar-project/wollok-lsp-ide/blob/dfec6ed514756fc4899c7858eb3f71b1fb105c7e/server/src/server.ts#L57). Esa línea tira un error que es el que publiqué en el primer mensaje:

    TypeError: Cannot read properties of null (reading 'typeSystem')


Si se comenta o se quita, el server sigue sin aparente problema. Luego el cliente se queja de que intenta registrar [didChangeWorkspaceFolders](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders).

Para hacer pruebas, establecí el valor de [esta](https://github.com/uqbar-project/wollok-lsp-ide/blob/dfec6ed514756fc4899c7858eb3f71b1fb105c7e/server/src/server.ts#L67) variable a `false`.

Con esto, el cliente se queja una vez más de que el server intenta registrar una capacidad no soportada que es [didChangeConfigurationNotification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration). Se hace [acá](https://github.com/uqbar-project/wollok-lsp-ide/blob/dfec6ed514756fc4899c7858eb3f71b1fb105c7e/server/src/server.ts#L98).

Nuevamente, borrando la línea, se continúa. Con esto, el cliente se puede conectar al server, y envía requests, pero como dije antes no responde. Se queda haciendo nada.

**Comment by tomi2108** [comment]
@tralph3  Existe algun discord para no plagar las issues? El del README.md esta roto

**Comment by tralph3** [comment]
Las issues están para esto.

**Comment by tomi2108** [comment]
Logre hacer funcionar el LSP hardcodeando el workspace folder en el servidor :?
![imagen](https://github.com/uqbar-project/wollok-lsp-ide/assets/72281044/8a534d10-f860-4443-86b6-8eae1d5e930f)
Estas son las capacidades que me devuelve el servidor 
![imagen](https://github.com/uqbar-project/wollok-lsp-ide/assets/72281044/7f045c93-7212-4ac9-bc98-cf01608494b4)
No veo nada de notification que me decis, quizas me estoy perdiendo de algo

**Comment by tralph3** [comment]
¿Podrías pasar tu configuración de NeoVim para el server?

**Comment by tomi2108** [comment]
```lua

function()
  vim.lsp.start_client({
    name = "wollokLSP",
    cmd = { "node", "path_al_server_js", "--stdio" },
    workspace_folders = {
      {
        uri = "file:path_al_dir_de_prueba", -- esto parece no estar funcionando por ahora... es lo que tuve que hardcodear en el server
        name = "cwd",
      },
    },
    -- before_init = function(params)
    --   local file = io.open("wollok_req.log", "w")
    --   io.output(file)
    --   io.write(dump(params))
    -- end,
    on_init = function(client, params)
      -- local file = io.open("wollok_res.log", "w")
      -- io.output(file)
      -- io.write(dump(params))
      vim.lsp.buf_attach_client(0, client.id) 
    end,
  })
end

```

Eso es todo para iniciar el server y conectarlo al buffer actual, después hay otras cosas para hacer el coloreado de sintaxis
